In [3]:
### Importing packages
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
import os
import sqlite3

In [4]:
### Load the data
df = pd.read_excel("Health_Science_Dataset.xlsx", header=1)

In [4]:
### Header for Data
df

,Data As Of,Start Week,End Week,MMWRyear,MMWRweek,Week Ending Date,Group,Indicator,Jurisdiction,Age Group,COVID-19 Deaths,Total Deaths,Pneumonia Deaths,Influenza Deaths,Pneumonia or Influenza,"Pneumonia, Influenza, or COVID-19 Deaths"
0,11/02/2023,12/29/2019,01/04/2020,2020,1,01/04/2020,By Week,Week-ending,United States,All Ages,0.0,60028.0,4102.0,432.0,4534.0,4534.0
1,11/02/2023,12/29/2019,01/04/2020,2020,1,01/04/2020,By Week,Week-ending,United States,0-17 years,0.0,667.0,19.0,22.0,41.0,41.0
2,11/02/2023,12/29/2019,01/04/2020,2020,1,01/04/2020,By Week,Week-ending,United States,18-64 years,0.0,14706.0,767.0,183.0,950.0,950.0
3,11/02/2023,12/29/2019,01/04/2020,2020,1,01/04/2020,By Week,Week-ending,United States,65 years and over,0.0,44655.0,3316.0,227.0,3543.0,3543.0
4,11/02/2023,12/29/2019,01/04/2020,2020,1,01/04/2020,By Week,Week-ending,Alabama,All Ages,0.0,1098.0,67.0,NaN,72.0,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50395,11/02/2023,10/22/2023,10/28/2023,2023,43,10/28/2023,By Week,Week-ending,HHS Region 9,65 years and over,43.0,1970.0,128.0,NaN,129.0,155.0
50396,11/02/2023,10/22/2023,10/28/2023,2023,43,10/28/2023,By Week,Week-ending,HHS Region 10,All Ages,14.0,435.0,26.0,0.0,26.0,36.0
50397,11/02/2023,10/22/2023,10/28/2023,2023,43,10/28/2023,By Week,Week-ending,HHS Region 10,0-17 years,0.0,0.0,0.0,0.0,0.0,0.0
50398,11/02/2023,10/22/2023,10/28/2023,2023,43,10/28/2023,By Week,Week-ending,HHS Region 10,18-64 years,0.0,61.0,NaN,0.0,NaN,NaN
50399,11/02/2023,10/22/2023,10/28/2023,2023,43,10/28/2023,By Week,Week-ending,HHS Region 10,65 years and over,14.0,374.0,23.0,0.0,23.0,33.0

In [6]:
### Column names
[f"{col}: {df[col].dtype}" for col in df.columns]

['Data As Of: object',
 'Start Week: object',
 'End Week: object',
 'MMWRyear: int64',
 'MMWRweek: int64',
 'Week Ending Date: object',
 'Group: object',
 'Indicator: object',
 'Jurisdiction: object',
 'Age Group: object',
 'COVID-19 Deaths: float64',
 'Total Deaths: float64',
 'Pneumonia Deaths: float64',
 'Influenza Deaths: float64',
 'Pneumonia or Influenza: float64',
 'Pneumonia, Influenza, or COVID-19 Deaths: float64']

In [13]:
# String
for col_idx in [6, 7, 8, 9]:
    col_name = df.columns[col_idx]
    df[col_name] = df[col_name].astype(str)

# Dates
for col_idx in [0, 1, 2, 5]:
    col_name = df.columns[col_idx]
    df[col_name] = pd.to_datetime(df[col_name], format='%Y-%m-%d %H:%M:%S', errors='coerce')

# Year
df.iloc[:, 3] = pd.to_datetime(df.iloc[:, 3], format='%Y', errors='coerce')

# Integer
for col_idx in [4] + list(range(10, 16)):
    col_name = df.columns[col_idx]
    df[col_name] = df[col_name].apply(lambda x: int(x) if pd.notna(x) else x)

In [14]:
### Column names
[f"{col}: {df[col].dtype}" for col in df.columns]

['Data As Of: datetime64[ns]',
 'Start Week: datetime64[ns]',
 'End Week: datetime64[ns]',
 'MMWRyear: datetime64[ns]',
 'MMWRweek: int64',
 'Week Ending Date: datetime64[ns]',
 'Group: object',
 'Indicator: object',
 'Jurisdiction: object',
 'Age Group: object',
 'COVID-19 Deaths: float64',
 'Total Deaths: float64',
 'Pneumonia Deaths: float64',
 'Influenza Deaths: float64',
 'Pneumonia or Influenza: float64',
 'Pneumonia, Influenza, or COVID-19 Deaths: float64']